document.addEventListener("DOMContentLoaded", () => {
    const tableBody = document.getElementById("calTableBody");
    const addRowBtn = document.getElementById("addRowBtn");
    const exportPdfBtn = document.getElementById("exportPdfBtn");
    const avgErrorCell = document.getElementById("avgErrorCell");

    // Initialize with 3 baseline measurement rows
    for (let i = 1; i <= 3; i++) {
        addRow(i);
    }

    addRowBtn.addEventListener("click", () => {
        const rowCount = tableBody.children.length + 1;
        addRow(rowCount);
    });

    // Auto-format environmental fields to 2 decimal places
    document.querySelectorAll(".env-input").forEach(input => {
        input.addEventListener("blur", (e) => {
            let val = e.target.value.trim();
            if (val !== "" && !isNaN(val)) {
                e.target.value = parseFloat(val).toFixed(2);
            }
        });
    });

    function addRow(runNumber) {
        const tr = document.createElement("tr");
        tr.innerHTML = `
            <td class="text-center fw-bold">${runNumber}</td>
            <td><input type="text" class="table-input std-input" placeholder="20.00" value="20.00"></td>
            <td><input type="text" class="table-input ind-input" placeholder="0.00"></td>
            <td><input type="text" class="table-input err-input" readonly placeholder="0.00%"></td>
            <td><input type="text" class="table-input remark-input" placeholder="Pass / Fail / Notes"></td>
        `;
        tableBody.appendChild(tr);
        attachRowEvents(tr);
    }

    function attachRowEvents(row) {
        const stdInput = row.querySelector(".std-input");
        const indInput = row.querySelector(".ind-input");
        
        [stdInput, indInput].forEach(input => {
            input.addEventListener("blur", (e) => formatAndCalculate(row, e.target));
            input.addEventListener("keyup", (e) => {
                if (e.key === "Enter") formatAndCalculate(row, e.target);
            });
        });
    }

    function formatAndCalculate(row, activeInput) {
        let val = activeInput.value.trim();
        
        // Format to 2 decimal places if numerical entry
        if (val !== "" && !isNaN(val)) {
            activeInput.value = parseFloat(val).toFixed(2);
        }

        calculateRowError(row);
        calculateOverallAverage();
    }

    function calculateRowError(row) {
        const stdVal = parseFloat(row.querySelector(".std-input").value);
        const indVal = parseFloat(row.querySelector(".ind-input").value);
        const errInput = row.querySelector(".err-input");

        // Percentage Error Formula: ((Indicated - Standard) / Standard) * 100
        if (!isNaN(stdVal) && !isNaN(indVal) && stdVal !== 0) {
            const errorPercent = ((indVal - stdVal) / stdVal) * 100;
            errInput.value = errorPercent.toFixed(2) + "%";
        } else {
            errInput.value = "N/A";
        }
    }

    function calculateOverallAverage() {
        const errInputs = document.querySelectorAll(".err-input");
        let totalError = 0;
        let validCount = 0;

        errInputs.forEach(input => {
            const val = parseFloat(input.value.replace("%", ""));
            if (!isNaN(val)) {
                totalError += val;
                validCount++;
            }
        });

        if (validCount > 0) {
            const avg = totalError / validCount;
            avgErrorCell.textContent = avg.toFixed(2) + "%";
        } else {
            avgErrorCell.textContent = "0.00%";
        }
    }

    // PDF Export Logic with Restored Page Boundaries & Multi-Page Rules
    exportPdfBtn.addEventListener("click", () => {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });

        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        const margin = 14;

        // Page Header Helper
        const addHeader = (title) => {
            doc.setFontSize(14);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(13, 110, 253);
            doc.text(title, margin, 15);
            doc.setDrawColor(200, 200, 200);
            doc.line(margin, 18, pageWidth - margin, 18);
        };

        // Footer Helper for Page Numbers
        const addFooter = (currentPage, totalPages) => {
            doc.setFontSize(8);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(128, 128, 128);
            doc.text(`Page ${currentPage} of ${totalPages} - Generated by Calibration Portal`, margin, pageHeight - 10);
            doc.text(new Date().toLocaleDateString(), pageWidth - margin - 20, pageHeight - 10);
        };

        // --- PAGE 1: Parts 1, 2, and 3 ---
        addHeader("EQUIPMENT CALIBRATION & INSPECTION REPORT");

        // Part 1 Table
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        doc.text("Part 1: General Information & Asset Identification", margin, 24);

        const part1Data = [
            ["Client Name", document.getElementById("clientName").value, "Certificate No.", document.getElementById("certNo").value],
            ["Equipment Desc.", document.getElementById("equipDesc").value, "Serial Number", document.getElementById("serialNo").value],
            ["Inspection Date", document.getElementById("inspectDate").value, "Location", document.getElementById("location").value],
            ["Make / Model", document.getElementById("makeModel").value, "Product Type", document.getElementById("productType").value]
        ];

        doc.autoTable({
            startY: 27,
            body: part1Data,
            theme: 'grid',
            styles: { fontSize: 8, cellPadding: 2 },
            columnStyles: { 0: { fontStyle: 'bold', fillColor: [245, 245, 245] }, 2: { fontStyle: 'bold', fillColor: [245, 245, 245] } },
            margin: { left: margin, right: margin }
        });

        // Part 2 Table
        let currentY = doc.lastAutoTable.finalY + 8;
        doc.text("Part 2: Calibration Measurements & Calculations", margin, currentY);

        const calRows = document.querySelectorAll("#calTableBody tr");
        const part2Data = [];

        calRows.forEach((row, idx) => {
            const std = row.querySelector(".std-input").value;
            const ind = row.querySelector(".ind-input").value;
            const err = row.querySelector(".err-input").value;
            const rem = row.querySelector(".remark-input").value;
            part2Data.push([idx + 1, std, ind, err, rem]);
        });

        part2Data.push([{ content: "Average Error", colSpan: 3, styles: { halign: 'right', fontStyle: 'bold' } }, avgErrorCell.textContent, ""]);

        doc.autoTable({
            startY: currentY + 3,
            head: [["Run #", "Standard Measure (L)", "Indicated Display (L)", "Error (%)", "Remarks"]],
            body: part2Data,
            theme: 'striped',
            headStyles: { fillColor: [13, 110, 253] },
            styles: { fontSize: 8, cellPadding: 2 },
            margin: { left: margin, right: margin }
        });

        // Part 3 Table
        currentY = doc.lastAutoTable.finalY + 8;
        doc.text("Part 3: Environmental Conditions & Pre-Test Checks", margin, currentY);

        const part3Data = [
            ["Ambient Temp (°C)", document.getElementById("ambTemp").value, "Product Temp (°C)", document.getElementById("prodTemp").value],
            ["Reference Density (kg/m³)", document.getElementById("density").value, "Visual Integrity", document.getElementById("visualCheck").value]
        ];

        doc.autoTable({
            startY: currentY + 3,
            body: part3Data,
            theme: 'grid',
            styles: { fontSize: 8, cellPadding: 2 },
            columnStyles: { 0: { fontStyle: 'bold', fillColor: [245, 245, 245] }, 2: { fontStyle: 'bold', fillColor: [245, 245, 245] } },
            margin: { left: margin, right: margin }
        });

        // --- PAGE 2: Boundary Break for Traceability, Verdict & Sign-offs ---
        doc.addPage();
        addHeader("EQUIPMENT CALIBRATION REPORT (Cont.)");

        // Part 4 Table
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        doc.text("Part 4: Traceability & Seal Register", margin, 24);

        const part4Data = [
            ["Prover Tank / Standard ID", document.getElementById("proverId").value, "Traceability Cert No.", document.getElementById("traceCert").value],
            ["Old Seal Serial No.", document.getElementById("oldSeal").value, "New Seal Serial No.", document.getElementById("newSeal").value]
        ];

        doc.autoTable({
            startY: 27,
            body: part4Data,
            theme: 'grid',
            styles: { fontSize: 8, cellPadding: 2 },
            columnStyles: { 0: { fontStyle: 'bold', fillColor: [245, 245, 245] }, 2: { fontStyle: 'bold', fillColor: [245, 245, 245] } },
            margin: { left: margin, right: margin }
        });

        // Part 5 Table & Verdict
        currentY = doc.lastAutoTable.finalY + 8;
        doc.text("Part 5: Compliance Verdict & Authorization Sign-Offs", margin, currentY);

        const verdict = document.getElementById("finalVerdict").value;
        const notes = document.getElementById("techNotes").value;

        const part5Data = [
            ["Overall Final Verdict", verdict, "Inspector Notes", notes],
            ["Lead Inspector Name", document.getElementById("inspectorName").value, "Client Representative", document.getElementById("clientRep").value],
            ["Inspector Signature", document.getElementById("inspSig").value, "Client Signature", document.getElementById("clientSig").value]
        ];

        doc.autoTable({
            startY: currentY + 3,
            body: part5Data,
            theme: 'grid',
            styles: { fontSize: 8, cellPadding: 3 },
            columnStyles: { 0: { fontStyle: 'bold', fillColor: [245, 245, 245] }, 2: { fontStyle: 'bold', fillColor: [245, 245, 245] } },
            margin: { left: margin, right: margin }
        });

        // Apply page footers across pages
        const totalPages = doc.internal.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
            doc.setPage(i);
            addFooter(i, totalPages);
        }

        doc.save("Complete_Calibration_Certificate.pdf");
    });
});
